AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

  FullDomainName:
    Type: String
    Description: The full domain name (img.example.com)
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

  AcmCertificateArn:
    Type: String
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "arn:aws:acm:.*"

Mappings:
  RegionMap:
    us-east-1:
      S3WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
    ap-northeast-1:
      S3WebsiteEndpoint: s3-website-ap-northeast-1.amazonaws.com

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HttpRedirectCode: 307
              HostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
              Protocol: https
              ReplaceKeyPrefixWith: prod?key=
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60
      Environment:
        Variables:
          BUCKET: !Ref ImageBucket
          URL: !Join ["", ["https://", !Ref FullDomainName]]
      Policies:
          Statement:
            - Resource: !Sub arn:aws:s3:::${ImageBucket}/*
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${ImageBucket}/*

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref FullDomainName
        HttpVersion: http2
        PriceClass: PriceClass_All
        Origins:
          - DomainName: !Join [., [!Ref 'ImageBucket', !FindInMap [RegionMap, !Ref 'AWS::Region', S3WebsiteEndpoint]]]
            Id: s3bucket
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: s3bucket
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0

        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only

  DNSRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'DomainName', .]]
      RecordSets:
        - Name: !Ref 'FullDomainName'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]
        - Name: !Ref 'FullDomainName'
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]

Outputs:
  BucketWebsiteUrl:
    Value: !Join ["", ["https://", !Ref FullDomainName]]
  Bucket:
    Value: !Ref ImageBucket
